### ISSUE TITLE
Motion Warning Integration

### ISSUE THREAD

**Issue by SkyNerdT1** [phgelado/guardmypi#10]
Currently, the motion warning code  is integrated with the Human and Pet detection code using YOLO with threading. While that the code currently functions it runs with a very low fps rate, which is exaggerated when it is run on the RPi. We need to find ways to optimise this code as it will form part of the main.cpp run on the final release

**Comment by MagnusBC98** [comment]
It transpires YOLO networks require far more processing power than the Pi can realistically handle. We will instead use Haar/LBP cascades as these have already been tested on the Pi and run smoothly in real-time. There are already pretrained models in the OpenCV library that can detect for example a human's upper body so this should be suitable, however we can also do LBP training if needed since it is not too time-consuming.

**Comment by SkyNerdT1** [comment]
I agree LBP training will not take long. Should be straightforward to get a database of human outlines. A couple of options there. With the program outline already tested with the YOLO code. It will be easy enough to change the human detection code to the new method just as a substitute.

**Comment by SkyNerdT1** [comment]
Code integrating the motion warning and Human detection is now finalised and ready to be brought into main. Will create a pull request.
